/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppModelswapRouteImport } from './routes/_app.modelswap'
import { Route as AppMemsearchRouteImport } from './routes/_app.memsearch'
import { Route as AppMemoryRouteImport } from './routes/_app.memory'
import { Route as AppInfraRouteImport } from './routes/_app.infra'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDelegationRouteImport } from './routes/_app.delegation'
import { Route as AppCodegraphRouteImport } from './routes/_app.codegraph'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdIssuesIssueIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModelswapRoute = AppModelswapRouteImport.update({
  id: '/modelswap',
  path: '/modelswap',
  getParentRoute: () => AppRoute,
} as any)
const AppMemsearchRoute = AppMemsearchRouteImport.update({
  id: '/memsearch',
  path: '/memsearch',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppInfraRoute = AppInfraRouteImport.update({
  id: '/infra',
  path: '/infra',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDelegationRoute = AppDelegationRouteImport.update({
  id: '/delegation',
  path: '/delegation',
  getParentRoute: () => AppRoute,
} as any)
const AppCodegraphRoute = AppCodegraphRouteImport.update({
  id: '/codegraph',
  path: '/codegraph',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIssuesIssueIdRoute =
  AppProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId',
    path: '/projects/$projectId/issues/$issueId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof AppChatRoute
  '/codegraph': typeof AppCodegraphRoute
  '/delegation': typeof AppDelegationRoute
  '/documents': typeof AppDocumentsRoute
  '/infra': typeof AppInfraRoute
  '/memory': typeof AppMemoryRoute
  '/memsearch': typeof AppMemsearchRoute
  '/modelswap': typeof AppModelswapRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof AppChatRoute
  '/codegraph': typeof AppCodegraphRoute
  '/delegation': typeof AppDelegationRoute
  '/documents': typeof AppDocumentsRoute
  '/infra': typeof AppInfraRoute
  '/memory': typeof AppMemoryRoute
  '/memsearch': typeof AppMemsearchRoute
  '/modelswap': typeof AppModelswapRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/codegraph': typeof AppCodegraphRoute
  '/_app/delegation': typeof AppDelegationRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/infra': typeof AppInfraRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/memsearch': typeof AppMemsearchRoute
  '/_app/modelswap': typeof AppModelswapRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/projects/$projectId_/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/codegraph'
    | '/delegation'
    | '/documents'
    | '/infra'
    | '/memory'
    | '/memsearch'
    | '/modelswap'
    | '/projects/$projectId'
    | '/projects/$projectId/issues/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/codegraph'
    | '/delegation'
    | '/documents'
    | '/infra'
    | '/memory'
    | '/memsearch'
    | '/modelswap'
    | '/projects/$projectId'
    | '/projects/$projectId/issues/$issueId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/chat'
    | '/_app/codegraph'
    | '/_app/delegation'
    | '/_app/documents'
    | '/_app/infra'
    | '/_app/memory'
    | '/_app/memsearch'
    | '/_app/modelswap'
    | '/_app/projects/$projectId'
    | '/_app/projects/$projectId_/issues/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/modelswap': {
      id: '/_app/modelswap'
      path: '/modelswap'
      fullPath: '/modelswap'
      preLoaderRoute: typeof AppModelswapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memsearch': {
      id: '/_app/memsearch'
      path: '/memsearch'
      fullPath: '/memsearch'
      preLoaderRoute: typeof AppMemsearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infra': {
      id: '/_app/infra'
      path: '/infra'
      fullPath: '/infra'
      preLoaderRoute: typeof AppInfraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delegation': {
      id: '/_app/delegation'
      path: '/delegation'
      fullPath: '/delegation'
      preLoaderRoute: typeof AppDelegationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/codegraph': {
      id: '/_app/codegraph'
      path: '/codegraph'
      fullPath: '/codegraph'
      preLoaderRoute: typeof AppCodegraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId': {
      id: '/_app/projects/$projectId_/issues/$issueId'
      path: '/projects/$projectId/issues/$issueId'
      fullPath: '/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCodegraphRoute: typeof AppCodegraphRoute
  AppDelegationRoute: typeof AppDelegationRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppInfraRoute: typeof AppInfraRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppMemsearchRoute: typeof AppMemsearchRoute
  AppModelswapRoute: typeof AppModelswapRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsProjectIdIssuesIssueIdRoute: typeof AppProjectsProjectIdIssuesIssueIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCodegraphRoute: AppCodegraphRoute,
  AppDelegationRoute: AppDelegationRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppInfraRoute: AppInfraRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppMemsearchRoute: AppMemsearchRoute,
  AppModelswapRoute: AppModelswapRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsProjectIdIssuesIssueIdRoute:
    AppProjectsProjectIdIssuesIssueIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
