/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMemoryRouteImport } from './routes/_app.memory'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdIssuesIssueIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIssuesIssueIdRoute =
  AppProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId',
    path: '/projects/$projectId/issues/$issueId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof AppChatRoute
  '/documents': typeof AppDocumentsRoute
  '/memory': typeof AppMemoryRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof AppChatRoute
  '/documents': typeof AppDocumentsRoute
  '/memory': typeof AppMemoryRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/projects/$projectId_/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/documents'
    | '/memory'
    | '/projects/$projectId'
    | '/projects/$projectId/issues/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/documents'
    | '/memory'
    | '/projects/$projectId'
    | '/projects/$projectId/issues/$issueId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/chat'
    | '/_app/documents'
    | '/_app/memory'
    | '/_app/projects/$projectId'
    | '/_app/projects/$projectId_/issues/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId': {
      id: '/_app/projects/$projectId_/issues/$issueId'
      path: '/projects/$projectId/issues/$issueId'
      fullPath: '/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsProjectIdIssuesIssueIdRoute: typeof AppProjectsProjectIdIssuesIssueIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsProjectIdIssuesIssueIdRoute:
    AppProjectsProjectIdIssuesIssueIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
